apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapicloudtest1-deployment
  labels:
    app: WebApiCloudTest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApiCloudTest1	  
  template:
    metadata:
      labels:
        app: WebApiCloudTest1
    spec:
      containers:
      - name: webapicloudtest1
        image: seshacr.azurecr.io/webapicloudtestdockerimage:27
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisec
---
apiVersion: v1
kind: Service
metadata:
  name: webapicloudtest1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApiCloudTest1